// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Warehouse.Data;

#nullable disable

namespace Warehouse.Data.Migrations
{
    [DbContext(typeof(WarehouseDBContext))]
    [Migration("20260708185725_AddQuantityToMovements")]
    partial class AddQuantityToMovements
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Warehouse.Data.Entities.Bins", b =>
                {
                    b.Property<int>("Bin_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Bin_Id"));

                    b.Property<string>("Bin_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Location_Id")
                        .HasColumnType("int");

                    b.Property<bool>("RealBin")
                        .HasColumnType("bit");

                    b.HasKey("Bin_Id");

                    b.HasIndex("Location_Id");

                    b.ToTable("Bins");

                    b.HasData(
                        new
                        {
                            Bin_Id = 1,
                            Bin_Name = "100-01A",
                            Location_Id = 1,
                            RealBin = true
                        },
                        new
                        {
                            Bin_Id = 2,
                            Bin_Name = "100-01B",
                            Location_Id = 1,
                            RealBin = true
                        },
                        new
                        {
                            Bin_Id = 3,
                            Bin_Name = "100-01C",
                            Location_Id = 1,
                            RealBin = true
                        },
                        new
                        {
                            Bin_Id = 4,
                            Bin_Name = "100-01D",
                            Location_Id = 1,
                            RealBin = true
                        },
                        new
                        {
                            Bin_Id = 5,
                            Bin_Name = "100-01E",
                            Location_Id = 1,
                            RealBin = true
                        },
                        new
                        {
                            Bin_Id = 6,
                            Bin_Name = "100-02A",
                            Location_Id = 1,
                            RealBin = true
                        },
                        new
                        {
                            Bin_Id = 7,
                            Bin_Name = "100-02B",
                            Location_Id = 1,
                            RealBin = true
                        },
                        new
                        {
                            Bin_Id = 8,
                            Bin_Name = "100-02C",
                            Location_Id = 1,
                            RealBin = true
                        },
                        new
                        {
                            Bin_Id = 9,
                            Bin_Name = "100-02D",
                            Location_Id = 1,
                            RealBin = true
                        },
                        new
                        {
                            Bin_Id = 10,
                            Bin_Name = "100-02E",
                            Location_Id = 1,
                            RealBin = true
                        },
                        new
                        {
                            Bin_Id = 11,
                            Bin_Name = "",
                            Location_Id = 2,
                            RealBin = false
                        },
                        new
                        {
                            Bin_Id = 12,
                            Bin_Name = "",
                            Location_Id = 3,
                            RealBin = false
                        });
                });

            modelBuilder.Entity("Warehouse.Data.Entities.Customers", b =>
                {
                    b.Property<int>("Customer_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Customer_Id"));

                    b.Property<string>("Customer_Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Customer_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Customer_Id");

                    b.HasIndex("Customer_Email")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Customer_Id = 1,
                            Customer_Email = "RouterUniversal@example.com",
                            Customer_Name = "Router Universals"
                        });
                });

            modelBuilder.Entity("Warehouse.Data.Entities.LocatedMaterials", b =>
                {
                    b.Property<int>("LocatedMaterials_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocatedMaterials_Id"));

                    b.Property<int>("Bin_Id")
                        .HasColumnType("int");

                    b.Property<int>("Material_Id")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("LocatedMaterials_Id");

                    b.HasIndex("Bin_Id");

                    b.HasIndex("Material_Id");

                    b.ToTable("LocatedMaterialas");
                });

            modelBuilder.Entity("Warehouse.Data.Entities.Locations", b =>
                {
                    b.Property<int>("Location_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Location_Id"));

                    b.Property<string>("Location_Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Location_Id");

                    b.HasIndex("Location_Name")
                        .IsUnique();

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Location_Id = 1,
                            Location_Name = "0100"
                        },
                        new
                        {
                            Location_Id = 2,
                            Location_Name = "0101"
                        },
                        new
                        {
                            Location_Id = 3,
                            Location_Name = "0102"
                        });
                });

            modelBuilder.Entity("Warehouse.Data.Entities.MaterialMovements", b =>
                {
                    b.Property<int>("MaterialMovement_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaterialMovement_Id"));

                    b.Property<int>("Material_Id")
                        .HasColumnType("int");

                    b.Property<int>("Movement_Id")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("MaterialMovement_Id");

                    b.HasIndex("Material_Id");

                    b.HasIndex("Movement_Id");

                    b.ToTable("MaterialMovements");
                });

            modelBuilder.Entity("Warehouse.Data.Entities.Materials", b =>
                {
                    b.Property<int>("Material_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Material_Id"));

                    b.Property<string>("Material_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Material_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Vendor_Id")
                        .HasColumnType("int");

                    b.HasKey("Material_Id");

                    b.HasIndex("Material_Name")
                        .IsUnique();

                    b.HasIndex("Vendor_Id");

                    b.ToTable("Materials");

                    b.HasData(
                        new
                        {
                            Material_Id = 1,
                            Material_Description = "Circuit type A for router",
                            Material_Name = "Circuit A",
                            Vendor_Id = 2
                        },
                        new
                        {
                            Material_Id = 2,
                            Material_Description = "Casing for Router",
                            Material_Name = "Casing A",
                            Vendor_Id = 3
                        },
                        new
                        {
                            Material_Id = 3,
                            Material_Description = "Screw for router",
                            Material_Name = "Screw A",
                            Vendor_Id = 4
                        },
                        new
                        {
                            Material_Id = 4,
                            Material_Description = "Circuit type B for fast router",
                            Material_Name = "Circuit B",
                            Vendor_Id = 2
                        },
                        new
                        {
                            Material_Id = 5,
                            Material_Description = "Manufactered Router ready for shipping",
                            Material_Name = "Router",
                            Vendor_Id = 1
                        },
                        new
                        {
                            Material_Id = 6,
                            Material_Description = "Manufactered Fast Router ready for shipping",
                            Material_Name = "Fast Router",
                            Vendor_Id = 1
                        });
                });

            modelBuilder.Entity("Warehouse.Data.Entities.MaterialsByModels", b =>
                {
                    b.Property<int>("MaterialByModel_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaterialByModel_Id"));

                    b.Property<int>("Material_Id")
                        .HasColumnType("int");

                    b.Property<int>("Model_Id")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("MaterialByModel_Id");

                    b.HasIndex("Material_Id");

                    b.HasIndex("Model_Id");

                    b.ToTable("MaterialsByModels");

                    b.HasData(
                        new
                        {
                            MaterialByModel_Id = 1,
                            Material_Id = 1,
                            Model_Id = 1,
                            Quantity = 1
                        },
                        new
                        {
                            MaterialByModel_Id = 2,
                            Material_Id = 2,
                            Model_Id = 1,
                            Quantity = 1
                        },
                        new
                        {
                            MaterialByModel_Id = 3,
                            Material_Id = 3,
                            Model_Id = 1,
                            Quantity = 4
                        },
                        new
                        {
                            MaterialByModel_Id = 4,
                            Material_Id = 4,
                            Model_Id = 2,
                            Quantity = 1
                        },
                        new
                        {
                            MaterialByModel_Id = 5,
                            Material_Id = 2,
                            Model_Id = 2,
                            Quantity = 1
                        },
                        new
                        {
                            MaterialByModel_Id = 6,
                            Material_Id = 3,
                            Model_Id = 2,
                            Quantity = 4
                        });
                });

            modelBuilder.Entity("Warehouse.Data.Entities.MaterialsByShipments", b =>
                {
                    b.Property<int>("MaterialsByShioment_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaterialsByShioment_Id"));

                    b.Property<int>("Material_Id")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Shipment_Id")
                        .HasColumnType("int");

                    b.HasKey("MaterialsByShioment_Id");

                    b.HasIndex("Material_Id");

                    b.HasIndex("Shipment_Id");

                    b.ToTable("MaterialsByShipments");
                });

            modelBuilder.Entity("Warehouse.Data.Entities.Models", b =>
                {
                    b.Property<int>("Model_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Model_Id"));

                    b.Property<string>("Model_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("New_Material_Id")
                        .HasColumnType("int");

                    b.HasKey("Model_Id");

                    b.HasIndex("Model_Name")
                        .IsUnique();

                    b.HasIndex("New_Material_Id");

                    b.ToTable("Models");

                    b.HasData(
                        new
                        {
                            Model_Id = 1,
                            Model_Name = "Router",
                            New_Material_Id = 5
                        },
                        new
                        {
                            Model_Id = 2,
                            Model_Name = "Fast Router",
                            New_Material_Id = 6
                        });
                });

            modelBuilder.Entity("Warehouse.Data.Entities.Movements", b =>
                {
                    b.Property<int>("Movement_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Movement_Id"));

                    b.Property<int>("LastBinLocation_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Movement_Time")
                        .HasColumnType("datetime2");

                    b.Property<int>("NewBinLocation_Id")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("User_Id")
                        .HasColumnType("int");

                    b.HasKey("Movement_Id");

                    b.HasIndex("LastBinLocation_Id");

                    b.HasIndex("NewBinLocation_Id");

                    b.HasIndex("User_Id");

                    b.ToTable("Movements");
                });

            modelBuilder.Entity("Warehouse.Data.Entities.Shipments", b =>
                {
                    b.Property<int>("Shipment_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Shipment_Id"));

                    b.Property<int>("Customer_Id")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("Sale_Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateOnly>("Shipment_Date")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Shipment_Id");

                    b.HasIndex("Customer_Id");

                    b.ToTable("Shipments");
                });

            modelBuilder.Entity("Warehouse.Data.Entities.Users", b =>
                {
                    b.Property<int>("User_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("User_Id"));

                    b.Property<string>("User_Adress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("User_Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("User_Fullname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("User_Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("User_Id");

                    b.HasIndex("User_Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            User_Id = 1,
                            User_Adress = "Cuauhtemoc #72",
                            User_Email = "jesus.quintero7478@alumnos.udg.mx",
                            User_Fullname = "Jesus Eduardo Quintero",
                            User_Password = "JesusEduardo"
                        },
                        new
                        {
                            User_Id = 2,
                            User_Adress = "Ramon Corona #53",
                            User_Email = "jorge.flores0258@alumnos.udg.mx",
                            User_Fullname = "Jorge Flores Kuan",
                            User_Password = "JorgeFlores"
                        });
                });

            modelBuilder.Entity("Warehouse.Data.Entities.Vendors", b =>
                {
                    b.Property<int>("Vendor_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Vendor_Id"));

                    b.Property<string>("Vendor_Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Vendor_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Vendor_Id");

                    b.HasIndex("Vendor_Email")
                        .IsUnique();

                    b.HasIndex("Vendor_Name")
                        .IsUnique();

                    b.ToTable("Vendors");

                    b.HasData(
                        new
                        {
                            Vendor_Id = 1,
                            Vendor_Email = "BossMail@example.com",
                            Vendor_Name = "Production Line"
                        },
                        new
                        {
                            Vendor_Id = 2,
                            Vendor_Email = "UniversalCircuits@example.com",
                            Vendor_Name = "Universal Circuits"
                        },
                        new
                        {
                            Vendor_Id = 3,
                            Vendor_Email = "UniversalPlastics@example.com",
                            Vendor_Name = "Universal Plastics"
                        },
                        new
                        {
                            Vendor_Id = 4,
                            Vendor_Email = "UniversalSteels@example.com",
                            Vendor_Name = "Universal Steels"
                        });
                });

            modelBuilder.Entity("Warehouse.Data.Entities.Bins", b =>
                {
                    b.HasOne("Warehouse.Data.Entities.Locations", "Location")
                        .WithMany("Bins")
                        .HasForeignKey("Location_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Warehouse.Data.Entities.LocatedMaterials", b =>
                {
                    b.HasOne("Warehouse.Data.Entities.Bins", "Bin")
                        .WithMany("LocatedMaterials")
                        .HasForeignKey("Bin_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Warehouse.Data.Entities.Materials", "Material")
                        .WithMany("LocatedMaterials")
                        .HasForeignKey("Material_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Bin");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("Warehouse.Data.Entities.MaterialMovements", b =>
                {
                    b.HasOne("Warehouse.Data.Entities.Materials", "Material")
                        .WithMany("MaterialMovements")
                        .HasForeignKey("Material_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Warehouse.Data.Entities.Movements", "Movement")
                        .WithMany("MaterialMovements")
                        .HasForeignKey("Movement_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Movement");
                });

            modelBuilder.Entity("Warehouse.Data.Entities.Materials", b =>
                {
                    b.HasOne("Warehouse.Data.Entities.Vendors", "vendor")
                        .WithMany("Materials")
                        .HasForeignKey("Vendor_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("vendor");
                });

            modelBuilder.Entity("Warehouse.Data.Entities.MaterialsByModels", b =>
                {
                    b.HasOne("Warehouse.Data.Entities.Materials", "Material")
                        .WithMany("MaterialsByModels")
                        .HasForeignKey("Material_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Warehouse.Data.Entities.Models", "model")
                        .WithMany("materialsByModels")
                        .HasForeignKey("Model_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("model");
                });

            modelBuilder.Entity("Warehouse.Data.Entities.MaterialsByShipments", b =>
                {
                    b.HasOne("Warehouse.Data.Entities.Materials", "Material")
                        .WithMany("MaterialsByShipments")
                        .HasForeignKey("Material_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Warehouse.Data.Entities.Shipments", "Shipment")
                        .WithMany("MaterialsByShipments")
                        .HasForeignKey("Shipment_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("Warehouse.Data.Entities.Models", b =>
                {
                    b.HasOne("Warehouse.Data.Entities.Materials", "New_Material")
                        .WithMany("Models")
                        .HasForeignKey("New_Material_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("New_Material");
                });

            modelBuilder.Entity("Warehouse.Data.Entities.Movements", b =>
                {
                    b.HasOne("Warehouse.Data.Entities.Bins", "LastBinLocation")
                        .WithMany()
                        .HasForeignKey("LastBinLocation_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Warehouse.Data.Entities.Bins", "NewBinLocation")
                        .WithMany()
                        .HasForeignKey("NewBinLocation_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Warehouse.Data.Entities.Users", "User")
                        .WithMany("Movements")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LastBinLocation");

                    b.Navigation("NewBinLocation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Warehouse.Data.Entities.Shipments", b =>
                {
                    b.HasOne("Warehouse.Data.Entities.Customers", "Customer")
                        .WithMany("Shipments")
                        .HasForeignKey("Customer_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Warehouse.Data.Entities.Bins", b =>
                {
                    b.Navigation("LocatedMaterials");
                });

            modelBuilder.Entity("Warehouse.Data.Entities.Customers", b =>
                {
                    b.Navigation("Shipments");
                });

            modelBuilder.Entity("Warehouse.Data.Entities.Locations", b =>
                {
                    b.Navigation("Bins");
                });

            modelBuilder.Entity("Warehouse.Data.Entities.Materials", b =>
                {
                    b.Navigation("LocatedMaterials");

                    b.Navigation("MaterialMovements");

                    b.Navigation("MaterialsByModels");

                    b.Navigation("MaterialsByShipments");

                    b.Navigation("Models");
                });

            modelBuilder.Entity("Warehouse.Data.Entities.Models", b =>
                {
                    b.Navigation("materialsByModels");
                });

            modelBuilder.Entity("Warehouse.Data.Entities.Movements", b =>
                {
                    b.Navigation("MaterialMovements");
                });

            modelBuilder.Entity("Warehouse.Data.Entities.Shipments", b =>
                {
                    b.Navigation("MaterialsByShipments");
                });

            modelBuilder.Entity("Warehouse.Data.Entities.Users", b =>
                {
                    b.Navigation("Movements");
                });

            modelBuilder.Entity("Warehouse.Data.Entities.Vendors", b =>
                {
                    b.Navigation("Materials");
                });
#pragma warning restore 612, 618
        }
    }
}
